name: 'AWS SAM Deploy (Alpine 3.15)'
description: 'Deploys AWS SAM Stack with Alpine 3.15 Dockerfile'
author: 'Jan Alfred Richter <falnyr@gmail.com>'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
